apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falco-talon.fullname" . }}-rules
  namespace: {{ include "falco-talon.namespace" . }}
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
data:
  rules.yaml: |-
{{- range $file := .Values.config.rulesFiles -}}
{{ $fileContent := $.Files.Get . }}
{{- $fileContent | nindent 4 -}}
{{- end -}}
